### ISSUE TITLE
стили в переменных

### ISSUE THREAD

**Issue by Geksanit** [NikitaLem/first_task_cv#1]
Привет.
![image](https://user-images.githubusercontent.com/31949379/45917154-79f35a80-be9b-11e8-827e-d89989aa4ee2.png)
Почему все стили в переменных ? Это ведь не удобно.

**Comment by NikitaLem** [comment]
Привет! Тогда я только знакомился со stylus и старался использовать его "фишки", в число которых входила и возможность сохранять стили в переменные. Тут они неуместны конечно. Хорошо, я это поправлю.

**Comment by NikitaLem** [comment]
> Привет.
> ![image](https://user-images.githubusercontent.com/31949379/45917154-79f35a80-be9b-11e8-827e-d89989aa4ee2.png)
> Почему все стили в переменных ? Это ведь не удобно.

@Geksanit 
Исправлено.

**Comment by NikitaLem** [comment]
@Geksanit

**Comment by NikitaLem** [comment]
> Привет.
> ![image](https://user-images.githubusercontent.com/31949379/45917154-79f35a80-be9b-11e8-827e-d89989aa4ee2.png)
> Почему все стили в переменных ? Это ведь не удобно.

Исправлено.
