### ISSUE TITLE
Контакты

### ISSUE THREAD

**Issue by Geksanit** [NikitaLem/first_task_cv#11]
для контактов добавь ссылки
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78ibe/
для ссылки на сайт есть дополнительный пункт в стандартах.

**Comment by Geksanit** [comment]
у ссылки на сайт должен быть атрибут `target` и `rel`
[как в стандартах](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_7gmev/)

**Comment by NikitaLem** [comment]
Да. Прошу прощения. Забыл, что в данном ссылка является ссылкой на внешний сайт.
