### ISSUE TITLE
Папки dist и docs

### ISSUE THREAD

**Issue by chmnkh** [NikitaLem/first_task_cv#13]
насколько я понял (если неправильно, поправь):
dist не используется сейчас вообще
docs выполняет как раз таки функцию dist, т.е. в него все бандлится

Если все верно, то у тебя должен остаться один dist, куда будет сборка падать, а docs - уйти в небытие. Ибо то, что у тебя одна папка вовсе не используется - косяк, и то, что docs падает сборка - тоже, потому что интуитивно в папках типа "docs" ожидаешь  увидеть документацию, или типа того, но никак не результат сборки)

**Comment by NikitaLem** [comment]
@chmnkh 
Да, всё верно. dist сейчас не используется, и бандлится всё в docs.

Почему есть эти две папки: изначально папкой куда все бандлилось была папка dist, но когда появилась необходимость выложить страничку на гитхаб пейджес, пришлось создать папку docs, так как гитхаб берет файлы из именно из этой папки. (возможно, я таки не до конца разобрался с гитхаб пейджес и можно было указать другой путь до нужных файлов).
Хорошо, я уберу папку docs и снова укажу в качестве пути папки dist. ;)
![image](https://user-images.githubusercontent.com/35275071/46403393-31059680-c724-11e8-8217-efd79add08f2.png)
