### ISSUE TITLE
Называть элементы по смыслу, а не по внешнему виду

### ISSUE THREAD

**Issue by chmnkh** [NikitaLem/first_task_cv#17]
Пример: header__circle.
А если я захочу его вдруг квадратным сделать?

**Comment by chmnkh** [comment]
pre-symbol: правильно, что dot заменить решил, но там на мой взгляд лучше бы подошло что-нибудь типа list-mark, что-то такое. pre-symbol - какая-то странная штука)
post-symbol: тут немного перестарался, потому что именно в этом случае сложно для этой линии какую-то смысловую нагрузку придумать, чисто декоративный какой-то элемент, и в принципе имя line подходило нормально. А post-symbol очень надуманно и неестественно выглядит.
В остальном норм.

**Comment by chmnkh** [comment]
в profile параметры не исправил
и, раз уж мы здесь
`.profile__text. `
что за точка в конце?)

**Comment by NikitaLem** [comment]
![image](https://user-images.githubusercontent.com/35275071/46619664-7e2ea180-cb44-11e8-99ef-b53aadcd0495.png)
Точка в конце -- это часть синтаксиса интерполяции pug'а. Хм, а какие параметры в profile не исправлены? :)

**Comment by chmnkh** [comment]
> ![image](https://user-images.githubusercontent.com/35275071/46619664-7e2ea180-cb44-11e8-99ef-b53aadcd0495.png)
> Точка в конце -- это часть синтаксиса интерполяции pug'а.

принял

> Хм, а какие параметры в profile не исправлены? :)

light/boldText
