### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Geksanit** [NikitaLem/first_task_cv#2]
![image](https://user-images.githubusercontent.com/31949379/45917180-0140ce00-be9c-11e8-88ec-6766935ea04a.png)
На широких экранах лучше добавить поля по-бокам.

**Comment by Geksanit** [comment]
а вот что на мобилах
![image](https://user-images.githubusercontent.com/31949379/45917194-54b31c00-be9c-11e8-8b3d-1b6e2f4b85bf.png)

**Comment by NikitaLem** [comment]
@Geksanit 
Добавил поля на широких мониторах и исправил верстку для мобилок.
