### ISSUE TITLE
Объект с входными параметрами

### ISSUE THREAD

**Issue by chmnkh** [NikitaLem/first_task_cv#22]
1) `- var personName = { firstName: "Name Here", surname: "surname", vacancy: "graphic designer" }`
это почему vacancy каким-то образом с personName связано? может переменную иначе как-то назвать?)
2) `- var headersArr = [{ title: "profile", imgSrc: "images/profile.png", }, ...`
идея передавать имена хэдеров и иконки для них - на мой взгляд странная. Фактически, внутри main-content ты знаешь, в каком порядке у тебя блоки будут располагаться и, следовательно, когда будут какие хэдеры. При этом ты зачем-то ждешь масив хэдеров из входных параметров, хотя хэдеры и их порядок в общем-то определен: сначала будет хэдер с профайлом, потом блок профайл, потом хэдер с контактом и блок контакт, и так далее.

**Comment by chmnkh** [comment]
vacancy-то было не обязательно переименовывать)
но тут можешь на свое усмотрение: оставить subInfo или вернуть vacancy
закрывать не буду, чтобы ты это точно прочитал, закрой сам, как прочтешь

**Comment by chmnkh** [comment]
из макета кстати вакансия пропала после этих изменений видимо, не забудь вернуть.

**Comment by NikitaLem** [comment]
Вернул vacancy. Макет поправил.
