### ISSUE TITLE
Добавить gitignore

### ISSUE THREAD

**Issue by chmnkh** [NikitaLem/first_task_cv#23]
В gitignore добавить файлы, которые не нужны в репе.
Ситуация сейчас: я клонирую репо, устанавливаю пакеты, они не в гитигноре, из-за чего гит думает, что это новые незакоммиченные изменения. Итого, я не могу запуллиться, что-то не сделав с этими пакетами.

**Comment by NikitaLem** [comment]
Если я правильно понял проблему, то дело в том, что у меня сам gitignore был добавлен в gitignore :)

**Comment by chmnkh** [comment]
Видимо да)
