### ISSUE TITLE
Не использовать модификаторы без класса элемента

### ISSUE THREAD

**Issue by chmnkh** [NikitaLem/first_task_cv#27]
`span.software__level_empty` так писать неправильно. Когда ты модифицируешь элемент, у тебя на нем должно быть всегда минимум 2 класса: класс элемента + класс модификатора. Правильно было бы `span.software__level.software__level_empty`. Иначе в модификаторах особого смысла нету, потому что они тогда не _расширяют_ стили элемента, а просто задают какие-то новые. А чтобы расширить стили, приходится писать какие-то костыли, типа 
```
  &__level
    display flex
    flex-wrap nowrap
    margin-top 1.41vw

    &_empty
      @extends $software_level
      background-color #e6e6e6
      flex-grow 1

    &_full
      @extends $software_level
      background-color #3d6cb0
```
тогда как на деле, у тебя $software_level стили должны быть включены в элемент software__level, и у тебя не должно быть необходимости руками такие экстенды писать.

**Comment by chmnkh** [comment]
Прочти еще раз коммент выше супер-внимательно и посмотри, что  у тебя в level-container'e лежит.

**Comment by NikitaLem** [comment]
Ох. Уже совсем не заметил что не исправил даже.
