### ISSUE TITLE
элемент снаружи блока

### ISSUE THREAD

**Issue by Geksanit** [NikitaLem/first_task_cv#3]
![image](https://user-images.githubusercontent.com/31949379/45917218-b3789580-be9c-11e8-8910-49b66b1c58ae.png)
почему блок `.names` обёрнут в свой элемент `.names_pushed-top` ? т.е. элемент используется вне блока?
и другие блоки тоже.

**Comment by NikitaLem** [comment]
@Geksanit 
Переименовал контейнеры.

**Comment by Geksanit** [comment]
Теперь они названы как блоки и у них есть внешнее позиционирование, а блокам внешнее позиционирование задавать нельзя.

**Comment by Geksanit** [comment]
`skills` по прежнему содержится в `skills__container`

**Comment by Geksanit** [comment]
Блоки по-прежнему внешне спозиционированны. А действительно ли они должны быть блоками? [Внешняя геометрия и позиционирование](https://ru.bem.info/methodology/css/#%D0%92%D0%BD%D0%B5%D1%88%D0%BD%D1%8F%D1%8F-%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F-%D0%B8-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) - тут это решается использованием миксов, но миксы у нас не приветствуются, есть другое решение - элементы-обёртки.
