### ISSUE TITLE
Дублирование стилей.

### ISSUE THREAD

**Issue by Geksanit** [NikitaLem/first_task_cv#8]
![image](https://user-images.githubusercontent.com/31949379/46256196-8f870680-c4d1-11e8-8a1a-72a29785b232.png)
Задумайся над тем что ты будешь делать, если модификаторов придётся делать 1000, 10000, ...?
Если не догадаешься как это сделать в pug, тогда подскажу )))

**Comment by NikitaLem** [comment]
![image](https://user-images.githubusercontent.com/35275071/46259321-d2f56b00-c4f9-11e8-9e99-01bc9a706d8c.png)
![image](https://user-images.githubusercontent.com/35275071/46259330-df79c380-c4f9-11e8-9b5d-54919350b273.png)
Добавил цикл в миксин, и переработал стили. Получилось вот так. Правильное решение? :)

**Comment by Geksanit** [comment]
Это уже лучше, но можно проще.
`span(class="software__level_full" style="width: #{val}")`
