### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Geksanit** [NikitaLem/first_task_cv#9]
1. В скриптах нужно прописать путь до модуля, что бы гарантированно запускался локально установленный модуль.
2. dependencies - это модули необходимые для сборки в продакшн. devDependencies - всё остальное. раздели модули по этому принципу.

**Comment by Geksanit** [comment]
а почему в dependencies пусто ?

**Comment by NikitaLem** [comment]
@Geksanit 
В этом проекте нет зависимостей, которые были бы необходимыми в продакшене. Это ведь просто статичная страничка. :)

**Comment by Geksanit** [comment]
Ну и что, что статичная. Всё что работает на gh-pages - это и есть продакшн сборка. Есть же для этого специальный скрипт build, cоответственно всё что он использует -> в dependencies;

**Comment by Geksanit** [comment]
stylus и pug и другие модули тоже используются в build(попробуй их удалить и запустить:) ). т.е. в devDependencies должны остаться только "webpack-cli" и "webpack-dev-server"
